on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile
        uses: xu-cheng/latex-action@v2
        with:
          root_file: root.tex
          latexmk_use_lualatex: true
          latexmk_shell_escape: true

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          path: root.pdf
          name: root.pdf

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: root.pdf
          tag_name: "release-${{ github.sha }}"
