on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Compile document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: root.tex
          latexmk_use_lualatex: true
          latexmk_shell_escape: true
      - name: Upload document
        uses: actions/upload-artifact@v3
        with:
          path: root.pdf
