on:
  push:
    branches: [main, ci]
  workflow_dispatch:

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile
        uses: xu-cheng/latex-action@v2
        with:
          extra_system_packages: just
          compiler: just
          args: --verbose build
          root_file: root.tex

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          path: out/root.pdf
          name: root.pdf

      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ github.ref_name == 'main' }}
        with:
          files: out/root.pdf
          tag_name: "release-${{ github.sha }}"
